#!/usr/bin/env python3
"""Replace fabricated template experiences with real, verified tours.

Deletes:
  - 892 seasonal-template fakes ("Atelier cuisine X — Printemps", generated by
    seed_seasonal_experiences.py with template descriptions + invented prices)
  - duplicate "Circuit découverte de X" rows (69 extra copies)

Seeds ~40 real tours researched from live operator sites (Terres Touareg,
MzabTours, TOURSSET, Fancy Algeria, Roza Tour, Pelago/Viator, GoWithGuide,
Nomade Aventure, Ziguade Travel, Confidences Nomades, Riwaya Travel, Détours
Algérie). Every row carries `source` + `source_url` and `is_verified=true`.
Prices converted to DZD at the official Bank of Algeria rate (12 Aug 2026):
1 EUR = 153.33 DZD, 1 USD = 132.86 DZD. Dry-run with --dry-run.
"""

import argparse
import sys
import uuid
from datetime import datetime, timezone

import psycopg2
from psycopg2.extras import execute_values

DB_CONFIG = {
    "host": "localhost", "port": 5434,
    "dbname": "athar_db", "user": "athar", "password": "athar_pass",
}

EUR = 153.33
USD = 132.86


def eur(amount: float) -> float:
    return round(amount * EUR)


def usd(amount: float) -> float:
    return round(amount * USD)


# (title, category, wilaya_id, meeting_point, price_dzd, duration_h, max_p,
#  language, season, source, source_url, description)
REAL_TOURS = [
    # ── Djanet / Tassili n'Ajjer (56) ──
    ("Circuit Nord Tassili n'Ajjer : Vallée d'Iherir",
     "hiking", 56, "Aéroport de Djanet", eur(795), 7 * 8, 15, "fr", "autumn",
     "Terres Touareg / Algérie Tours",
     "https://www.algerie-tours.com/circuit-nord-tassili-najjer/",
     "Trek de 7 jours au nord du Tassili n'Ajjer, du Parc culturel classé UNESCO. "
     "Traversée de l'Erg Admer et ses gravures rupestres (la Vache qui pleure), "
     "oasis d'Iherir, canyon d'Essendilène et site de Tikoubaouine à l'arche de "
     "grès en forme d'éléphant. Bivouacs sous les étoiles, nuit en gîte et en "
     "maison touarègue. Départs saisonniers de septembre à avril."),
    ("Circuit Sud Tassili n'Ajjer : Tadrart Rouge",
     "hiking", 56, "Aéroport de Djanet", eur(710), 7 * 8, 10, "fr", "autumn",
     "MzabTours (agence depuis 1987)",
     "https://mzabtours.net/",
     "Circuit 4x4 de 7 jours dans la Tadrart Rouge, au sud du Parc du Tassili "
     "n'Ajjer : dunes de sable rouge, formations rocheuses spectaculaires et "
     "art rupestre préhistorique. Vols intérieurs inclus. Bivouac et pension "
     "complète."),
    ("Circuit Plateau Tassili n'Ajjer : Sefar",
     "hiking", 56, "Aéroport de Djanet", eur(1290), 9 * 8, 12, "fr", "autumn",
     "Terres Touareg",
     "https://www.terres-touareg.com/",
     "9 jours sur le plateau du Tassili n'Ajjer, le musée à ciel ouvert classé "
     "au patrimoine mondial de l'UNESCO. Fresques et gravures préhistoriques du "
     "labyrinthe de Sefar, campements nomades touaregs, bivouacs. Prochains "
     "départs en octobre-novembre."),
    ("S'biba : fêtes et immersion culturelle à Djanet",
     "cultural", 56, "Djanet", eur(900), 7 * 8, 10, "fr", "summer",
     "Terres Touareg",
     "https://www.terres-touareg.com/",
     "7 jours à Djanet pendant la S'Biba, célébration traditionnelle touareg "
     "(fin juin) : défilés, chants, danses et musiques. Immersion dans le "
     "monde touareg du Tassili n'Ajjer avec les guides locaux."),
    ("Djanet Tihoudayene : expédition dans le Tassili",
     "adventure", 56, "Abarbar, Djanet", eur(600), 7 * 8, 8, "fr", "autumn",
     "TOURSSET Sahara Tours",
     "https://toursset-dz.com/",
     "Expédition de 7 jours au départ de Djanet vers Tihoudayene, dans le "
     "massif du Tassili n'Ajjer. Paysages lunaires, peintures rupestres et "
     "immersion dans la culture touareg. Petits groupes, guides locaux."),
    ("Méharée touareg dans le Tassili n'Ajjer",
     "adventure", 56, "Djanet", eur(1300), 7 * 8, 8, "fr", "autumn",
     "Ihakettravels",
     "https://www.ihakettravels.com/nos-circuits",
     "Voyage en méharée à dos de chameau dans le désert algérien : dunes, "
     "canyons, gueltas et peintures rupestres, au rythme de la vie nomade "
     "touareg. Marches de 5 à 6 h par jour, bivouacs sous les étoiles."),

    # ── Tamanrasset / Hoggar (11) ──
    ("Le Tassili du Hoggar : joyau secret du Sahara",
     "hiking", 11, "Aéroport de Tamanrasset", eur(590), 8 * 8, 12, "fr", "autumn",
     "MzabTours (agence depuis 1987)",
     "https://mzabtours.net/",
     "8 jours dans le massif du Hoggar au départ de Tamanrasset : paysages de "
     "l'Ahaggar, guelta d'Imazeganène, gravures rupestres et rencontres "
     "touaregs. Vols intérieurs inclus, bivouac, pension complète."),
    ("Coucher de soleil sur l'Assekrem",
     "hiking", 11, "Tamanrasset", eur(480), 5 * 8, 10, "fr", "autumn",
     "MzabTours (agence depuis 1987)",
     "https://mzabtours.net/",
     "5 jours pour rejoindre l'ermitage du Père de Foucauld au sommet de "
     "l'Assekrem (2 780 m), l'un des plus beaux couchers de soleil du Sahara. "
     "Nuits en bivouac dans le massif du Hoggar."),

    # ── Ghardaïa / M'zab (47) ──
    ("Dans les ksour du M'zab",
     "cultural", 47, "Ghardaïa", eur(520), 5 * 8, 10, "fr", "spring",
     "MzabTours (agence depuis 1987)",
     "https://mzabtours.net/",
     "5 jours dans la vallée du M'zab, patrimoine mondial UNESCO : la "
     "pentapole mozabite (Ghardaïa, Beni Isguen, Melika, Bounoura, El Atteuf), "
     "ses ksour et son système d'irrigation millénaire. Visites guidées des "
     "mosquées, marchés et palmeraies."),

    # ── Algiers (16) ──
    ("Visite de la Casbah d'Alger",
     "cultural", 16, "Casbah, rue Aoua Abdelkader", usd(42.42), 3, 15, "fr", None,
     "Pelago",
     "https://www.pelago.com/en/activity/pl9dc8m13-algiers-casbah-visit-algiers/",
     "Visite guidée de 3 heures de la médina millénaire de la Casbah, classée "
     "au patrimoine mondial de l'UNESCO : ruelles étroites, palais ottomans, "
     "forts et points de vue sur la mer. Guide algérien expérimenté."),
    ("Circuit découverte d'Alger : Casbah, Bardo et Mémorial du Martyr",
     "tour", 16, "Alger", eur(69), 8, 150, "fr", None,
     "Roza Tour (agence de voyage agréée)",
     "https://rozatour-booking.com/tour/algiers-city-tour-casbah-bardo-martyrsmemorial",
     "Journée complète : Casbah UNESCO, Musée national du Bardo (archéologie), "
     "déjeuner traditionnel algérien et Mémorial du Martyr avec vue "
     "panoramique sur la Méditerranée. Guide professionnel, transferts en "
     "van climatisé, entrées et repas inclus."),
    ("Algiers City Tour",
     "tour", 16, "Alger centre", eur(120), 8, 15, "fr", None,
     "Fancy Algeria",
     "https://www.fancyalgeria.com/tour",
     "Tour de 8 heures de la ville d'Alger, la blanche : Casbah classée "
     "UNESCO, architecture mauresque et moderne, corniche et points de vue "
     "sur la Méditerranée. Transport et guide inclus."),
    ("Visite privée de la Casbah avec déjeuner traditionnel (Dar El Mahroussa)",
     "food", 16, "Bab El Oued, Casbah", usd(67.28), 5, 8, "fr", None,
     "Viator / Dar El Mahroussa",
     "https://www.viator.com/tours/Algiers/BEST-Casbah-Tour-and-Food-in-Algiers/d25745-429472P1",
     "Visite privée de 5 à 6 h de la Casbah avec déjeuner dans Dar El "
     "Mahroussa, la dernière maison de maître de la médina. Guide multilingue "
     "(FR/EN/AR), musées et entrées inclus."),

    # ── Oran (31) ──
    ("Oran Highlights Walking Tour",
     "tour", 31, "Place du 1er Novembre, Oran", usd(40), 4, 6, "fr", None,
     "GoWithGuide (guide local)",
     "https://gowithguide.com/algeria/tour/oran-oran-highlights-walking-tour-22804",
     "Visite à pied de 4 heures des monuments du centre d'Oran : vieille "
     "ville de Sidi Lhouari, places principales, architecture française et "
     "espagnole. Tour privé, guide francophone."),
    ("Oran City Tour",
     "tour", 31, "Oran centre", eur(120), 8, 15, "fr", None,
     "Fancy Algeria",
     "https://www.fancyalgeria.com/tour",
     "Tour de 8 heures de la deuxième ville d'Algérie : baie d'Oran, "
     "architecture française, église espagnole de Santa Cruz (XVIe siècle) et "
     "vieille ville. Guide et transport inclus."),
    ("Oran : balade dans El Bahia avec un local",
     "cultural", 31, "Oran", usd(50), 4, 7, "fr", None,
     "GoWithGuide (guide local)",
     "https://gowithguide.com/algeria/tour/oran-oran-walking-tour-of-el-bahia-with-a-local-17624",
     "Promenade de 4 heures dans le centre historique d'Oran, la « Joyeuse » : "
     "fort espagnol, vieille ville, quartier européen, mosquée ottomane du "
     "Pacha et jardins de Letang. Itinéraire personnalisable."),

    # ── Constantine (25) ──
    ("Constantine City Tour",
     "tour", 25, "Constantine centre", eur(120), 8, 15, "fr", None,
     "Fancy Algeria",
     "https://www.fancyalgeria.com/tour",
     "Tour de 8 heures de Constantine, la ville des ponts suspendus au-dessus "
     "des gorges du Rhumel : palais du Bey, musées, mosquées et panoramas "
     "spectaculaires. Guide et transport inclus."),
    ("L'Est algérien : Constantine, Ghoufi, Timgad, Djemila, Tiddis",
     "tour", 25, "Constantine", eur(790), 6 * 8, 12, "fr", "summer",
     "Confidences Nomades",
     "https://confidences-nomades.com/trip/circuit-est-algerien-constantine-ghoufi-timgad-djemila-tiddis/",
     "Circuit de 6 jours entre les villes suspendues et les sites romains "
     "classés UNESCO : Constantine, les balcons de Ghoufi dans les Aurès, "
     "Timgad (arc de Trajan, forum, théâtre), Djemila et Tiddis. Hébergement "
     "en maison d'hôte dont une nuit à Ghoufi."),

    # ── Tlemcen (13) ──
    ("Tlemcen City Tour : patrimoine arabo-andalou",
     "cultural", 13, "Tlemcen centre", eur(130), 8, 15, "fr", None,
     "Fancy Algeria",
     "https://www.fancyalgeria.com/tour",
     "Tour de 8 heures de Tlemcen, capitale zianide : mosquées et demeures "
     "arabo-andalouses, l'un des plus anciens bâtiments almoravides "
     "d'Algérie. Guide et transport inclus."),
    ("Oran, Mostaganem et Tlemcen (5 jours)",
     "tour", 13, "Oran", eur(640), 5 * 8, 10, "fr", None,
     "Roza Tour (agence de voyage agréée)",
     "https://rozatour-booking.com/",
     "Circuit de 5 jours dans l'Oranie : Oran et Santa Cruz, la côte de "
     "Mostaganem, puis le patrimoine arabo-andalou de Tlemcen. Hôtels, guide "
     "et pension inclus."),

    # ── Timgad (Batna 5) ──
    ("Timgad : la Pompéi africaine",
     "tour", 5, "Timgad, wilaya de Batna", eur(140), 8, 15, "fr", None,
     "Fancy Algeria",
     "https://www.fancyalgeria.com/tour",
     "Journée sur le site romain de Timgad, classé UNESCO : fondé par Trajan "
     "vers 100 ap. J.-C., plan en damier parfait, arc de Trajan, forum, "
     "thermes, théâtre et maisons à mosaïques. Guide et transport inclus."),

    # ── Djemila (Sétif 19) ──
    ("Djemila : la ville romaine des montagnes",
     "tour", 19, "Djemila, wilaya de Sétif", eur(140), 8, 15, "fr", None,
     "Fancy Algeria",
     "https://www.fancyalgeria.com/tour",
     "Journée sur le site de Djemila (Cuicul), l'un des plus beaux sites "
     "romains d'Algérie à 900 m d'altitude : forums, temples, arc de "
     "triomphe, thermes et musée aux mosaïques remarquables. Guide et "
     "transport inclus."),

    # ── Kabylie (Tizi Ouzou 15, Béjaïa 6) ──
    ("Randonnée en Kabylie : villages et sentiers du Djurdjura",
     "hiking", 15, "Alger", eur(2389), 13 * 8, 8, "fr", "autumn",
     "Nomade Aventure",
     "https://www.nomade-aventure.com/voyage-aventure/algerie/voyage-en-kabylie-algerie/alg06",
     "13 jours entre la Casbah d'Alger et les villages kabyles : massif du "
     "Djurdjura, ateliers de bijoux de Beni Yenni, poterie d'Amachras, "
     "monastère de Tibhirine et criques sauvages de Béjaïa. Randonnées "
     "encadrées par des guides locaux, hébergement en hôtel et maison "
     "d'hôtes."),
    ("Séjour en Kabylie : 7 jours entre Béjaïa et Tizi Ouzou",
     "tour", 15, "Alger ou Béjaïa", eur(890), 7 * 8, 8, "fr", "spring",
     "Ziguade Travel",
     "https://ziguadetravel.com/sejour-en-kabylie/",
     "Circuit de 7 jours entre la Méditerranée et le Djurdjura : Béjaïa et sa "
     "casbah, Cap Carbon, villages berbères, forêt de Belloua et ateliers "
     "d'artisanat kabyle. Base 2 voyageurs, pension complète, guide local."),
    ("Kabylie entre Djurdjura et Méditerranée",
     "hiking", 6, "Béjaïa", eur(790), 7 * 8, 12, "fr", "autumn",
     "Confidences Nomades",
     "https://confidences-nomades.com/trip/circuit-kabylie-au-coeur-de-la-culture-berbere/",
     "7 jours d'immersion en Kabylie : atelier de bijoux berbères à Beni "
     "Yenni, randonnées dans le parc de Gouraya jusqu'au phare de Cap Carbon, "
     "crique des Aiguades et vieille ville de Béjaïa."),
    ("Randonnée en Haute Kabylie : du Djurdjura aux villages d'oliviers",
     "hiking", 15, "Alger", eur(750), 8 * 8, 10, "fr", "summer",
     "Détours Algérie Voyages (depuis 1999)",
     "https://www.voyagealgerie.fr/circuit/randonnee-en-haute-kabylie-le-djurdjuraa",
     "8 jours à travers la chaîne du Djurdjura, qui dépasse partout les 2 000 "
     "m : cols de Tirourda et Azrou N'Thor, villages perchés, ateliers de "
     "Beni Yenni. Randonnées sur les chemins de bergers, gîtes kabyles."),

    # ── Béchar / Taghit (8) ──
    ("Route des Ksour : Béni Abbès et Taghit",
     "tour", 8, "Béchar", eur(620), 6 * 8, 10, "fr", "spring",
     "MzabTours (agence depuis 1987)",
     "https://mzabtours.net/",
     "6 jours sur la route des ksour de la Saoura : oasis de Béni Abbès, la "
     "perle du Saoura, dunes rouges de Taghit et ksour de la vallée de la "
     "Zousfana. Rencontres nomades, bivouacs et visites culturelles."),
]

SEASONAL_RE = r"— (Printemps|Été|Automne|Hiver)$"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--seed-only", action="store_true",
                        help="skip deletion, only insert real tours")
    args = parser.parse_args()

    conn = psycopg2.connect(**DB_CONFIG)
    conn.autocommit = False
    cur = conn.cursor()

    deleted = {"seasonal": 0, "dup_circuit": 0}

    if not args.seed_only:
        cur.execute("DELETE FROM experiences WHERE title ~ %s", (SEASONAL_RE,))
        deleted["seasonal"] = cur.rowcount
        print(f"Deleted {deleted['seasonal']} seasonal-template experiences.")

        cur.execute("""
            DELETE FROM experiences e
            USING experiences e2
            WHERE e.title = e2.title
              AND e.title LIKE 'Circuit découverte de %'
              AND e.id > e2.id
        """)
        deleted["dup_circuit"] = cur.rowcount
        print(f"Deleted {deleted['dup_circuit']} duplicate 'Circuit découverte' rows.")

    if args.dry_run:
        conn.rollback()
        cur.close()
        conn.close()
        print(f"[dry-run] {len(REAL_TOURS)} real tours to insert.")
        return

    conn.commit()

    # ── provider: use the "ATHAR Voyages" seeded agency as the operator carrier ──
    cur.execute("SELECT user_id FROM provider_profiles WHERE provider_type='agency' LIMIT 1")
    row = cur.fetchone()
    provider_id = row[0] if row else None
    if not provider_id:
        print("ERROR: no agency provider found; aborting.")
        cur.close()
        conn.close()
        sys.exit(1)

    rows = []
    for (title, category, wilaya_id, meeting_point, price, dur, max_p,
         lang, season, source, source_url, desc) in REAL_TOURS:
        rows.append((provider_id, title, category, desc, wilaya_id,
                     meeting_point, price, dur, max_p, lang, season,
                     source, source_url, True))

    execute_values(
        cur,
        """INSERT INTO experiences
           (id, provider_id, title, category, description, wilaya_id, meeting_point,
            price_dzd, duration_hours, max_participants, language, season,
            source, source_url, is_verified, status, created_at)
        VALUES %s
        ON CONFLICT DO NOTHING
        """,
        [(str(uuid.uuid4()), p, t, c, d, w, m, pr, du, mx, la, se, so, su, v, "active", datetime.now(timezone.utc))
         for (p, t, c, d, w, m, pr, du, mx, la, se, so, su, v) in rows],
    )
    conn.commit()

    cur.execute("""
        SELECT title FROM experiences
        WHERE source IS NOT NULL AND source != ''
        ORDER BY created_at DESC
    """)
    total = len(cur.fetchall())
    print(f"Inserted {len(REAL_TOURS)} real tours. Experiences with a source: {total}.")

    cur.close()
    conn.close()


if __name__ == "__main__":
    sys.exit(main())
