"""South-Algeria agent knowledge — compact DB-derived briefing.

Loads `app/agents/data/south_knowledge.json` (generated by
`scripts/data/generate_south_knowledge.py`) once and renders a compact
markdown briefing that agents can rely on for deep-south destinations
(reach, stays, restaurants, featured POIs). Everything in the briefing
is real data from the database — nothing fabricated.

`south_briefing(query)` returns the briefing text only when the query
references the south (wilaya names, Sahara/desert keywords, Tassili/
Ahaggar, etc.), so northern queries stay lean.
"""

from __future__ import annotations

import re
import unicodedata
from functools import lru_cache
from pathlib import Path

_KB_PATH = Path(__file__).resolve().parent / "data" / "south_knowledge.json"

_SOUTH_KEYWORDS = (
    "sahara",
    "desert",
    "desertique",
    "sud",
    "south",
    "tassili",
    "ahaggar",
    "hoggar",
    "assekrem",
    "touareg",
    "touaregs",
    "tuareg",
    "ksar",
    "ksour",
    "oasis",
    "erg",
    "tamanrasset",
    "djanet",
    "ghardaia",
    "ghardaïa",
    "ouargla",
    "adrar",
    "timimoun",
    "illizi",
    "bechar",
    "béchar",
    "tindouf",
    "beni abbes",
    "béni abbès",
    "in salah",
    "in-salah",
    "el meniaa",
    "bordj badji mokhtar",
    "حمّاد",
    "تمنراست",
    "جانت",
    "غرداية",
    "ورقلة",
    "أدرار",
    "تيميمون",
    "إليزي",
    "بشار",
    "تندوف",
    "بني عباس",
    "عين صالح",
    "المنيعة",
)


def _normalize(text: str) -> str:
    text = text.lower()
    text = unicodedata.normalize("NFKD", text)
    text = re.sub(r"[’']", " ", text)
    text = re.sub(r"[^a-z0-9\u0600-\u06FF\s]", "", text)
    return re.sub(r"\s+", " ", text).strip()


@lru_cache(maxsize=1)
def load_south_knowledge() -> dict:
    if not _KB_PATH.exists():
        return {"wilayas": {}, "intro": "", "operator_notes": {}}
    import json

    return json.loads(_KB_PATH.read_text(encoding="utf-8"))


def is_south_query(query: str) -> bool:
    if not query:
        return False
    q = _normalize(query)
    kb = load_south_knowledge()
    for wilaya in kb.get("wilayas", {}).values():
        name = _normalize(wilaya.get("name", ""))
        if name and name in q:
            return True
    return any(kw in q for kw in _SOUTH_KEYWORDS)


def last_user_turn(message_history: str | None) -> str:
    """Extract the most recent user turn from the message-history preamble."""
    if not message_history:
        return ""
    for line in reversed(message_history.splitlines()):
        if line.startswith("[User]:"):
            return line[len("[User]:") :].strip()
    return ""


def south_briefing(query: str) -> str:
    """Return the south-Algeria briefing if the query is south-related."""
    if not is_south_query(query):
        return ""
    kb = load_south_knowledge()
    if not kb.get("wilayas"):
        return ""

    parts = [
        "## SOUTH ALGERIA BRIEFING (real, DB-derived — prefer these facts over guessing)",
    ]
    if kb.get("intro"):
        parts.append(kb["intro"])
    notes = kb.get("operator_notes") or {}
    if notes.get("air_algerie"):
        parts.append(f"Air Algérie: {notes['air_algerie']}")
    if notes.get("taxis"):
        parts.append(f"Taxis: {notes['taxis']}")

    q = _normalize(query)
    matched = [wid for wid, w in kb["wilayas"].items() if _normalize(w.get("name", "")) in q]
    if matched:
        parts.append(
            "Per-wilaya (flights / taxis / stays / restaurants / featured) "
            f"for the {len(matched)} wilaya(s) in your query:"
        )
        wilayas = {wid: kb["wilayas"][wid] for wid in matched}
    else:
        parts.append("Per-wilaya (flights / taxis / stays / restaurants / featured):")
        wilayas = kb["wilayas"]

    for wid in sorted(wilayas, key=lambda k: wilayas[k]["name"]):
        w = kb["wilayas"][wid]
        flights = ", ".join(w["flights"]) if w["flights"] else "none in DB"
        taxis = ", ".join(w["taxis"]) if w["taxis"] else "none in DB"
        stays = (
            "; ".join(f"{s['name']} ({s['price_dzd']:.0f} DZD)" for s in w["stays"]) or "none in DB"
        )
        rests = ", ".join(w["restaurants"]) or "none in DB"
        feats = ", ".join(w["featured"]) or "none in DB"
        parts.append(
            f"- {w['name']} (wilaya {wid}): flights [{flights}]; "
            f"taxis [{taxis}]; stays: {stays}; restaurants: {rests}; "
            f"featured: {feats}."
        )
    return "\n".join(parts)
